name = "ArrayIteration"
uuid = "fad66f4c-51a1-49e8-bb49-ac0e2e1d46bd"
authors = ["Tim Holy <tim.holy@gmail.com>"]
version = "0.1.0"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
